export const schema = [
  { source: 'machine_id', output: 'machine_id', type: 'string', required: true, classification: 'identity', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'published', output: 'published', type: 'boolean', required: true, classification: 'publication', controlledValues: ['TRUE', 'FALSE'], numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'lifecycle_status', output: 'lifecycle_status', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'market', output: 'market', type: 'string', required: false, classification: 'source-metadata', controlledValues: ['AU', 'NZ'], numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'image_filename', output: 'image_filename', type: 'string', required: false, classification: 'image', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'image_alt_text', output: 'image_alt_text', type: 'string', required: false, classification: 'image', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'source_url', output: 'source_url', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'source_title', output: 'source_title', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'last_reviewed_date', output: 'last_reviewed_date', type: 'date-string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'notes', output: 'notes', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'machine', output: 'machine', type: 'string', required: true, classification: 'identity', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'manufacturer', output: 'manufacturer', type: 'string', required: true, classification: 'identity', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'country_of_manufacture', output: 'country_of_manufacture', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'model_year', output: 'model_year', type: 'integer', required: true, classification: 'identity', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'rated_hp', output: 'rated_hp', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'max_hp', output: 'max_hp', type: 'number', required: true, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'max_hp_with_ipm', output: 'max_hp_with_ipm', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'max_torque_nm', output: 'max_torque_nm', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'transmission', output: 'transmission', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'transmission_filter_tags', output: 'transmission_filter_tags', type: 'list', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'transmission_class', output: 'transmission_class', type: 'string', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'top_speed_filter', output: 'top_speed_filter', type: 'string', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'cylinders_filter', output: 'cylinders_filter', type: 'string', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'top_speed_kmh', output: 'top_speed_kmh', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'wheelbase_mm', output: 'wheelbase_mm', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'unladen_weight_kg', output: 'unladen_weight_kg', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'max_permissible_weight_40_kmh_kg', output: 'max_permissible_weight_40_kmh_kg', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'max_permissible_weight_50_kmh_kg', output: 'max_permissible_weight_50_kmh_kg', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'max_permissible_weight_60_kmh_kg', output: 'max_permissible_weight_60_kmh_kg', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'rated_hydraulic_flow_lpm', output: 'rated_hydraulic_flow_lpm', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'max_hydraulic_flow_lpm', output: 'max_hydraulic_flow_lpm', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'max_scvs', output: 'max_scvs', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'rear_hitch_capacity_kg', output: 'rear_hitch_capacity_kg', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'front_hitch_capacity_kg', output: 'front_hitch_capacity_kg', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'engine_capacity_l', output: 'engine_capacity_l', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'number_of_cylinders', output: 'number_of_cylinders', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'engine_manufacturer', output: 'engine_manufacturer', type: 'string', required: false, classification: 'source-metadata', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'cab_suspension', output: 'cab_suspension', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'fuel_capacity_l', output: 'fuel_capacity_l', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'engine_stage_tier', output: 'engine_stage_tier', type: 'string', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'adblue_tank_l', output: 'adblue_tank_l', type: 'number', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: true, missingValueBehavior: 'null' },
  { source: 'rear_pto_option', output: 'rear_pto_option', type: 'string', required: false, classification: 'specification', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' },
  { source: 'rear_pto_filter_tags', output: 'rear_pto_filter_tags', type: 'list', required: false, classification: 'filter', controlledValues: null, numericDeltaEligible: false, missingValueBehavior: 'null' }
];

export const expectedCsvHeader = schema.map((field) => field.source);
