export const fieldDefinitions = {
  machine_id: { type: 'id', required: true, output: 'id', group: 'control' },
  published: { type: 'boolean', required: true, output: 'published', group: 'control' },
  lifecycle_status: { type: 'string', output: 'lifecycleStatus', group: 'control' },
  market: { type: 'enum', required: true, values: ['AU', 'NZ', 'AU/NZ', 'UK', 'US'], output: 'market', group: 'control' },
  image_filename: { type: 'string', output: 'filename', group: 'image' },
  image_alt_text: { type: 'string', output: 'altText', group: 'image' },
  source_url: { type: 'string', output: 'url', group: 'source' },
  source_title: { type: 'string', output: 'title', group: 'source' },
  last_reviewed_date: { type: 'date', output: 'lastReviewedDate', group: 'source' },
  notes: { type: 'string', output: 'notes', group: 'source' },
  machine: { type: 'string', required: true, output: 'machine', group: 'identity' },
  manufacturer: { type: 'string', required: true, output: 'manufacturer', group: 'identity' },
  country_of_manufacture: { type: 'string', output: 'countryOfManufacture', group: 'specifications' },
  model_year: { type: 'integer', required: true, output: 'modelYear', group: 'identity' },
  rated_hp: { type: 'number', output: 'ratedHp', group: 'specifications' },
  max_hp: { type: 'number', output: 'maxHp', group: 'specifications' },
  max_hp_with_ipm: { type: 'number', output: 'maxHpWithIpm', group: 'specifications' },
  max_torque_nm: { type: 'number', output: 'maxTorqueNm', group: 'specifications' },
  transmission: { type: 'string', output: 'transmission', group: 'specifications' },
  transmission_filter_tags: { type: 'list', output: 'transmissionTags', group: 'filters' },
  transmission_class: { type: 'string', output: 'transmissionClass', group: 'filters' },
  top_speed_filter: { type: 'number', output: 'topSpeed', group: 'filters' },
  cylinders_filter: { type: 'integer', output: 'cylinders', group: 'filters' },
  top_speed_kmh: { type: 'flex', output: 'topSpeedKmh', group: 'specifications' },
  wheelbase_mm: { type: 'flex', output: 'wheelbaseMm', group: 'specifications' },
  unladen_weight_kg: { type: 'flex', output: 'unladenWeightKg', group: 'specifications' },
  max_permissible_weight_40_kmh_kg: { type: 'flex', output: 'maxPermissibleWeight40KmhKg', group: 'specifications' },
  max_permissible_weight_50_kmh_kg: { type: 'flex', output: 'maxPermissibleWeight50KmhKg', group: 'specifications' },
  max_permissible_weight_60_kmh_kg: { type: 'flex', output: 'maxPermissibleWeight60KmhKg', group: 'specifications' },
  rated_hydraulic_flow_lpm: { type: 'flex', output: 'ratedHydraulicFlowLpm', group: 'specifications' },
  max_hydraulic_flow_lpm: { type: 'flex', output: 'maxHydraulicFlowLpm', group: 'specifications' },
  max_scvs: { type: 'string', output: 'maxScvs', group: 'specifications' },
  rear_hitch_capacity_kg: { type: 'flex', output: 'rearHitchCapacityKg', group: 'specifications' },
  front_hitch_capacity_kg: { type: 'flex', output: 'frontHitchCapacityKg', group: 'specifications' },
  engine_capacity_l: { type: 'flex', output: 'engineCapacityL', group: 'specifications' },
  number_of_cylinders: { type: 'flex', output: 'numberOfCylinders', group: 'specifications' },
  engine_manufacturer: { type: 'string', output: 'engineManufacturer', group: 'specifications' },
  cab_suspension: { type: 'string', output: 'cabSuspension', group: 'specifications' },
  fuel_capacity_l: { type: 'flex', output: 'fuelCapacityL', group: 'specifications' },
  engine_stage_tier: { type: 'string', output: 'engineStageTier', group: 'specifications' },
  adblue_tank_l: { type: 'flex', output: 'adblueTankL', group: 'specifications' },
  rear_pto_option: { type: 'string', output: 'rearPtoOption', group: 'specifications' },
  rear_pto_filter_tags: { type: 'list', output: 'rearPtoTags', group: 'filters' }
};

export const expectedHeaders = Object.keys(fieldDefinitions);
export const displaySections = [
  { title: 'Machine', fields: ['manufacturer', 'machine', 'modelYear', 'market', 'countryOfManufacture'] },
  { title: 'Power and engine', fields: ['ratedHp', 'maxHp', 'maxHpWithIpm', 'maxTorqueNm', 'engineCapacityL', 'numberOfCylinders', 'engineManufacturer', 'engineStageTier'] },
  { title: 'Derived performance', fields: ['powerToWeightHpPerTonne', 'powerToWeightKwPerTonne'] },
  { title: 'Transmission and speed', fields: ['transmission', 'transmissionClass', 'topSpeedKmh'] },
  { title: 'Dimensions and weights', fields: ['wheelbaseMm', 'unladenWeightKg', 'maxPermissibleWeight40KmhKg', 'maxPermissibleWeight50KmhKg', 'maxPermissibleWeight60KmhKg'] },
  { title: 'Hydraulics and hitch', fields: ['ratedHydraulicFlowLpm', 'maxHydraulicFlowLpm', 'maxScvs', 'rearHitchCapacityKg', 'frontHitchCapacityKg'] },
  { title: 'Cab and capacities', fields: ['cabSuspension', 'fuelCapacityL', 'adblueTankL'] },
  { title: 'PTO', fields: ['rearPtoOption'] }
];
